---

# 1a. Create a playbook that runs against localhost.
# In this playbook, create a task that uses "include_tasks" and loads in an external sub-tasks file named "subtask1.yml".
# The task in the main playbook should have a loop that loops over four IP addresses.
# The sub-tasks file should have a "debug" task that prints out the IP address.

- name: Localhost play
  hosts: local
  gather_facts: False
  tasks:

    - name: include_tasks with loop
      ansible.builtin.include_tasks: subtask1.yml
      loop:
      - 192.168.1.1
      - 192.168.1.2
      - 192.168.1.3
      - 192.168.1.4
    
