---

# 2c. Convert exercise1c over to use "import_tasks" instead of "include_tasks".
# If no tags are defined in the main playbook (i.e. on the "import_tasks" task),
# then what happens upon ansible-playbook execution
# (in other words, you pass in a "tag" via ansible-playbook
# and that tag only exists in the sub-task file)?
# Does the sub-task execute or not? Why does the sub-task execute

- name: Localhost play
  hosts: local
  gather_facts: False
  tasks:

    - name: include subtask2.yml
      ansible.builtin.import_tasks: subtask2.yml