---

# 2. Use napalm_get_facts and the "get_lldp_neighbors()" method (filter: lldp_neighbors)
# to retrieve the LLDP neighbors from all of the Arista and Cisco IOS/IOS-XE devices.

# Reformat the retrieved data to print out the following table to standard output (in a somewhat readable way).
# Note, you might need to use the "stdout_callback = debug" to accomplish this (i.e. to make the output somewhat readable):
# ********* LLDP table for (cisco6) ********
# GigabitEthernet2: cisco5
# GigabitEthernet3: cisco5
# GigabitEthernet4: cisco5
# GigabitEthernet5: cisco5
# GigabitEthernet6: cisco5
# GigabitEthernet7: cisco5

# >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>
# The first entry should be the local interface and the second entry should be the remote peer that is visible via that interface.
# You should clearly indicate which device the LLDP data was retrieved from.

# You can loop through the data and use string concatenation to generate one large string (per device).
# You will subsequently output this string to the screen.

- name: NAPALM Cisco play
  hosts: cisco:arista
  vars:
    napalm_port:
      eos: 443
      ios: 22  
  tasks:

    - name: Retrieve lldp nei
      napalm.napalm.get_facts:
        filter: lldp_neighbors
        optional_args:
          port: "{{ napalm_port[ansible_network_os] }}"
    
    - name: Print
      ansible.builtin.debug:
        var: napalm_lldp_neighbors
    
    - name: Create list of local ints
      ansible.builtin.set_fact:
        intf_list: "{{ intf_list | default([]) + [item.key] }}"
      with_dict: "{{ napalm_lldp_neighbors }}"
    
    - name: Print2
      ansible.builtin.debug:
        var: intf_list
    
    - name: Create list of remote Device names
      ansible.builtin.set_fact:
        rem_dev: "{{ rem_dev | default([]) + [item.value[0].hostname] }}"
      with_dict: "{{ napalm_lldp_neighbors }}"

    - name: Print2
      ansible.builtin.debug:
        var: rem_dev
    
    - name: Create list of lists using zip
      ansible.builtin.set_fact:
        lldp_list: "{{ intf_list | zip(rem_dev) | list }}"

    - name: Create dict
      ansible.builtin.set_fact:
        lldp_dict: "{{ dict(lldp_list) }}"

    - name: Print3
      ansible.builtin.debug:
        msg: |
          "********* LLDP table for ({{inventory_hostname}}) ********" 
          {{ lldp_dict | to_nice_json  }}
          >>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"