---

# 3. Create a filter plugin that processes the "show ip arp" output from the four Cisco IOS/IOS-XE routers.
# The filter plugin should take the ARP output as a string
# It should return a dictionary where the key is the IP address and the value is the MAC address.

# Construct an Ansible playbook that retrieves "show ip arp" from the four Cisco IOS/IOS-XE routers.
# Process this ARP output through the new filter and verify that the new dictionary is properly returned for each device.

- name: Cisco play
  hosts: cisco
  gather_facts: False
  tasks:
    
    - name: Get show ip arp output from device
      cisco.ios.ios_command:
        commands: show ip arp
      register: sh_arp
    
    - name: Print
      ansible.builtin.debug:
        var: sh_arp.stdout[0]
    
    # Filters are in filter3.py in filter_plugins directory
    - name: Cisco ARP filter
      ansible.builtin.debug:
        msg: "{{ sh_arp.stdout[0] | ciscoarp}}"