---
# 6b. Add an additional set of tasks to use eos_command to execute "show ip arp | json".
# Once again register this output and print it to standard output.
# For the "show ip arp | json" output is a string returned or is structured data returned?

- name: Arista show ip arp
  hosts: arista
  gather_facts: False
  tasks:
    
    - name: Send sh ip arp to devices
      arista.eos.eos_command:
        commands:
          - show ip arp
      register: sh_arp

    - name: print output
      ansible.builtin.debug:
        var: sh_arp
    
    - name: Get back sh arp in JSON
      arista.eos.eos_command:
        commands:
          - show ip arp | json
      register: arp_j
    
    - name: Print JSON output
      ansible.builtin.debug:
        var: arp_j
      
       
