# 3c. Modify the debug task to print only the output of "show lldp neighbors" to stdout.
# You should be accessing my_variable["stdout_lines"][1]
# Alternatively, you could access my_variable["stdout"][1].

- name: NXOS command 
  hosts: nxos
  gather_facts: False
  tasks:

    - name: gather output from show commands
      cisco.nxos.nxos_command:
        # Pass list of commands
        commands:
          - show version
          - show lldp neighbors
      # Put output into variable
      register: show_cmds
      
    - name: print output of lldp nei only
      debug:
        var: show_cmds.stdout_lines[1]