---

# 4. Use the eos_vlans resource module to create a VLAN assigning it a name on all 4 Arista switches.
# The VLAN ID should be in the VLAN range from VLAN 200 to 299.

# After this VLAN is created, then use the eos_l2_interfaces resource module
# To assign that VLAN to one of the interfaces on all four of the Arista switches.
# You should either Ethernet5, Ethernet6, or Ethernet7 (do NOT use Ethernet1).
# Your VLAN ID, VLAN name, and interface name should be stored in either host_vars or group_vars.

# Using eos_command and a show command(s), verify that your VLAN exists.
# Plus the Ethernet interface you chose was assigned to that interface (I used "show vlan | json").
# This verification will probably require that you use an assert statements.

- name: Arista create vlan and assign to interface
  hosts: arista
  gather_facts: False
  tasks:

    - name: Create VLAN 407
      arista.eos.eos_vlans:
        config:
          - vlan_id: 407
            name: SAS_VLAN
            state: active
        state: merged

    - name: Assign Eth7 to VLAN created
      arista.eos.eos_l2_interfaces:
        config:
          - name: Ethernet7
            mode: access
            access:
              vlan: 407
        state: merged

    - name: Verify VLAN exists
      arista.eos.eos_command:
        commands: show vlan | json
      register: sh_vlan

    - name: Assert VLAN and interface
      ansible.builtin.assert:
        that:
          # Parse through dictionary to ensure we have both correct VLAN and interface
          - sh_vlan["stdout"][0]["vlans"]["407"]["interfaces"]["Ethernet7"] is defined
          - sh_vlan["stdout"][0]["vlans"]["407"]["name"] == "SAS_VLAN"
        success_msg: Both VLAN and interface are successfully configured
      
        
        