---

- name: Exercise1
  hosts: nxos
  gather_facts: False
  vars:
    fsm_template: "cisco_nxos_show_lldp_neighbors.template"

  tasks:
    - name: Executing command
      cisco.nxos.nxos_command:
        commands: show lldp neighbors
      register: output

    - name: TextFSM conversion
      ansible.builtin.set_fact:
        show_lldp: "{{ output.stdout[0] | parse_cli_textfsm(fsm_template) }}"

    - name: Create LLDP mapping of local interface to remote neighbor
      ansible.builtin.set_fact:
        lldp_map: "{{ lldp_map | default({}) | combine({item['LOCAL_INTERFACE']: item['NEIGHBOR']}) }}"
      loop: "{{ show_lldp }}"
      # Make the output more readable
      loop_control:
        label: ""

    - ansible.builtin.debug:
        var: lldp_map
