---
- name: Exercise5a
  hosts: nxos
  gather_facts: False

  tasks:
    - name: Executing command
      cisco.nxos.nxos_command:
        commands: show lldp neighbors
      register: output

    - ansible.builtin.set_fact:
        output: "{{ output.stdout[0] }}"

    - name: Print LLDP output
      ansible.builtin.debug:
        var: output.splitlines()

    - name: Extract LLDP columns using regular expressions
      ansible.builtin.set_fact:
        lldp: "{{ output | regex_findall('^(\\S+)\\s+(Eth\\S+)\\s+\\d+\\s+\\S+\\s+(Ethernet\\S+)', multiline=True) }}"

    - name: Print LLDP fields as a list
      ansible.builtin.debug: 
        msg: "{{ lldp }}"
