---

# 1b. Expand on your playbook that you created in exercise1a.
# Add tags to your playbook so that you can execute only "eos", "ios", or "junos" section of your playbook
# For example, if I provide the "eos" tag, then only the "eos" tasks should be run.

- name: Ansible network facts for show ip arp
  hosts: cisco:arista:juniper
  tasks:
  
    - name: EOS show ip arp
      arista.eos.eos_command:
        commands: show ip arp
      when: ansible_network_os == "eos"
      register: show_ip_arp_eos
      tags: eos
    
    - name: print EOS arp
      ansible.builtin.debug:
        var: show_ip_arp_eos
      when: ansible_network_os == "eos"
      tags: eos
    
    - name: IOS show ip arp
      cisco.ios.ios_command:
        commands: show ip arp
      when: ansible_network_os == "ios"
      register: show_ip_arp_ios
      tags: ios
    
    - name: JUNOS show ip arp
      junipernetworks.junos.junos_command:
        commands: show arp
      when: ansible_network_os == "junos"
      register: show_ip_arp_junos
      tags: junos
